// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udocjqcuyenoliqmzdwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkb2NqcWN1eWVub2xpcW16ZHdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI3OTQ1NzEsImV4cCI6MjA0ODM3MDU3MX0.KYsOOh7vZY3WAyA31K-3pLzt1-LA4s1ZsxHQcy4Rg5U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);